INSERT INTO board (code, name, category) VALUES
('a',   'Anime & Manga',1),
('b',   'Random',6),
('c',   'Anime/Cute',1),
('d',   'Hentai/Alternative',7),
('e',   'Ecchi',7),
('f',   'Flash',1),
('g',   'Technology',3),
('gif', 'Adult GIF',7),
('h',   'Hentai',7),
('hr',  'High Resolution',7),
('k',   'Weapons',3),
('m',   'Mecha',1),
('o',   'Auto',3),
('p',   'Photography',4),
('r',   'Adult Requests',7),
('s',   'Sexy Beautiful Women',7),
('t',   'Torrents',7),
('u',   'Yuri',7),
('v',   'Video Games',2),
('vg',  'Video Games General',2),
('vm',  'Video Games/Multiplayer',2),
('vmg', 'Video Games/Mobile',2),
('vr',  'Retro Games',2),
('vrpg','Video Games/RPG',2),
('vst', 'Video Games/Strategy',2),
('w',   'Anime/Wallpapers',1),
('wg',  'Wallpapers/General',4),
('i',   'Oekaki',4),
('ic',  'Artwork/Critique',4),
('r9k', 'ROBOT9001',6),
('s4s', 'Sh*t 4chan Says',6),
('vip', 'Very Important Posts',5),
('cm',  'Cute/Male',1),
('hm',  'Handsome Man',7),
('lgbt','Lesbian, Gay, Bisexual & Transgender',5),
('y',   'Yaoi',7),
('3',   '3DCG',4),
('aco', 'Adult Cartoons',7),
('adv', 'Advice',5),
('an',  'Animals & Nature',3),
('bant','International/Random',6),
('biz', 'Business & Finance',5),
('cgl', 'Cosplay & EGL',1),
('ck',  'Food & Cooking',4),
('co',  'Comics & Cartoons',3),
('diy', 'Do It Yourself',4),
('fa',  'Fashion',4),
('fit', 'Fitness',5),         
('gd',  'Graphic Design',4),         
('hc',  'Hardcore',7),
('his', 'History & Humanities',3),
('int', 'International',3),
('jp',  'Otaku Culture',1),
('lit', 'Literature',4),
('mlp', 'Pony',5),
('mu',  'Music',4),
('n',   'Transportation',1),         
('news','Current News',5),
('out', 'Outdoors',3),
('po',  'Papercraft & Origami',4),
('pol', 'Politically Incorrect',6),
('pw',  'Professional Wrestling',3),
('qst', 'Quests',4),
('sci', 'Science & Math',3),
('soc', 'Cams & Meetups',6),
('tg',  'Sports',3),
('toy', 'Toys',3),
('trv', 'Travel',5),
('tv',  'Television & Film',3),
('vp',  'Pokemon',2),
('vt',  'Virtual YouTubers',1),
('wsg', 'Worksafe GIF',4),
('wsr', 'Worksafe Requests',5),
('x',   'Paranormal',5),         
('xs',  'Extreme Sports',3);
